server:
  port: 8000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  config-location: "classpath:/mybatis-config.xml"
  type-aliases-package: com.neusoft.mora.bboot.domain
  mapper-locations: ["classpath:/com/neusoft/mora/bboot/service/**/*Repository.xml", "classpath:/me/puras/common/persistence/*Mapper.xml"]
