server:
  port: 8000

logging:
  level: debug
logging.level.me.puras: debug
org.mybatis: debug

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

mybatis:
  config-location: "classpath:/mybatis-config.xml"
  type-aliases-package: me.puras.mo.seed.moboot.domain
  mapper-locations: ["classpath:/me/puras/mo/seed/moboot/service/**/*Repository.xml", "classpath:/me/puras/common/persistence/*Mapper.xml"]
